/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int BOOL = 7;
  /** RegularExpression Id. */
  int UNIT = 8;
  /** RegularExpression Id. */
  int STRING = 9;
  /** RegularExpression Id. */
  int REF = 10;
  /** RegularExpression Id. */
  int LIST = 11;
  /** RegularExpression Id. */
  int STRUCT = 12;
  /** RegularExpression Id. */
  int UNION = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int TYPE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int STAR = 19;
  /** RegularExpression Id. */
  int LAZY_CONS_OP = 20;
  /** RegularExpression Id. */
  int NIL = 21;
  /** RegularExpression Id. */
  int BAR = 22;
  /** RegularExpression Id. */
  int DOT = 23;
  /** RegularExpression Id. */
  int TAG = 24;
  /** RegularExpression Id. */
  int CONS = 25;
  /** RegularExpression Id. */
  int CONS_OP = 26;
  /** RegularExpression Id. */
  int MATCH = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int LPAR = 29;
  /** RegularExpression Id. */
  int RPAR = 30;
  /** RegularExpression Id. */
  int LBRA = 31;
  /** RegularExpression Id. */
  int RBRA = 32;
  /** RegularExpression Id. */
  int EQUAL = 33;
  /** RegularExpression Id. */
  int COLON = 34;
  /** RegularExpression Id. */
  int SEMIC = 35;
  /** RegularExpression Id. */
  int TERM = 36;
  /** RegularExpression Id. */
  int COMMA = 37;
  /** RegularExpression Id. */
  int DEREF = 38;
  /** RegularExpression Id. */
  int AND = 39;
  /** RegularExpression Id. */
  int OR = 40;
  /** RegularExpression Id. */
  int EQ = 41;
  /** RegularExpression Id. */
  int GT = 42;
  /** RegularExpression Id. */
  int LT = 43;
  /** RegularExpression Id. */
  int GTEQ = 44;
  /** RegularExpression Id. */
  int LTEQ = 45;
  /** RegularExpression Id. */
  int DIF = 46;
  /** RegularExpression Id. */
  int NOT = 47;
  /** RegularExpression Id. */
  int ASSIGN = 48;
  /** RegularExpression Id. */
  int BOX = 49;
  /** RegularExpression Id. */
  int IF = 50;
  /** RegularExpression Id. */
  int ELSE = 51;
  /** RegularExpression Id. */
  int WHILE = 52;
  /** RegularExpression Id. */
  int PRINT = 53;
  /** RegularExpression Id. */
  int PRINTLN = 54;
  /** RegularExpression Id. */
  int FN = 55;
  /** RegularExpression Id. */
  int ARROW = 56;
  /** RegularExpression Id. */
  int LISTARROW = 57;
  /** RegularExpression Id. */
  int String = 58;
  /** RegularExpression Id. */
  int Id = 59;
  /** RegularExpression Id. */
  int Num = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"let\"",
    "\"int\"",
    "\"bool\"",
    "\"unit\"",
    "\"string\"",
    "\"ref\"",
    "\"list\"",
    "\"struct\"",
    "\"union\"",
    "\"true\"",
    "\"type\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\":?\"",
    "\"nil\"",
    "\"|\"",
    "\".\"",
    "\"#\"",
    "\"cons\"",
    "\"::\"",
    "\"match\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\":\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"!\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"~\"",
    "\":=\"",
    "\"box\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"println\"",
    "\"fn\"",
    "\"=>\"",
    "\"->\"",
    "<String>",
    "<Id>",
    "<Num>",
  };

}
